In [5]:
import numpy as np
import scipy as sc

#### ejercicio 1
##### intento 1

In [ ]:
def descompLU (A):
    # asumimos que la matriz es cuadrada, entoces A.shape[0] == A.shape[1]
    Ashape0= A.shape[0]

    a11 = A[0,0] # float
    A12 = A[0,1:] #list float
    A21 = A[1:, 0] #list float horizontal
    A22 = A[1:, 1:] # list list float
    u11 = a11
    U12 = A12
    L21 = A21/u11
    L22U22 = A22 - L21.reshape(-1,1)@U12.reshape(1,-1)
    
    if L22U22.shape != (2,2): #paso recursivo
        L22,U22= descompLU(L22U22)
        O = np.zeros(Ashape0 - 1)
        Ot = O.reshape(-1,1)
        L1 = np.concatenate(([1], O))
        print(L21.reshape(-1,1), L22)
        L2 = np.concatenate((L21.reshape(-1, 1), L22), axis=1)
        L  = np.concatenate(([L1],L2))
        U1 = np.concatenate(([u11], U12))
        U2 = np.concatenate((Ot,U22), axis = 1)
        U  = np.concatenate(([U1],U2))
        return L, U
    else: #caso base
        U22 = L22U22
        L   = np.array([[1,0],[L21[0],1]])
        #np.concatenate(np.array([[1,0]]),np.concatenate([L21],np.array([[1]]))) 
        U   = np.array([[u11,U12[0]],[0,U22[0][0]]])
        #np.concatenate(np.concatenate([u11],U12),np.concatenate(np.array([[0]]),U22)) 
        return L,U 

A = np.array([[1, 2, 0, 1], [4, 3, 2, 5], [2, 1, 0, 4], [3, 2, 1, 0]])
L, U = descompLU(A)
print("L:")
print(L)
print("U:")
print(U)

##### intento 2

In [3]:
def descompLU(A):
    n = A.shape[0]
    
    #Caso Base/Matriz de 1x1
    if n == 1:
        if A[0, 0] == 0:
            print("Error: La Matriz tiene un 0 en la diagonal.")
            return np.eye(1), A  # Devuelve la matriz identidad y A original
        else:
            return np.array([[1]]), A  # Matriz L es 1x1 con valor 1 y U es A original

    #Definiciones de bloques
         
    a11 = A[0, 0] # Obs: Python guarda este valor como un float  
    A12 = A[0, 1:]
    A21 = A[1:, 0] # Obs: Python guarda este vector en formato horizontal
    A22 = A[1:, 1:]

    #Definiciones de matrices complementarias
    
    I = np.eye(n)  # Matriz identidad de nxn
    I22 = np.eye(n-1) # Matriz identidad menor
    L = I
    U = np.zeros((n, n))  # Matriz de ceros de nxn
    
    
    # Calculos:
    
    # Calculamos u11 y U12
    if a11 == 0:
        print("Error: La Matriz tiene un 0 en la diagonal.")
        return L, A  # Devuelve la matriz identidad y A original
    
    u11 = a11
    U12 = A12
    
    # Calculamos L21
    L21 = A21 / u11
    
    
    # Calculamos L22 y U22 recursivamente
    L22U22 = A22 - L21.reshape(-1,1)@U12.reshape(1,-1)
    L22, U22 = descompLU(L22U22)
    
    #print("L22:")
    #print(L22)
    #print("U22:")
    #print(U22)
    #print("L22U22:")
    #print(L22U22)
    
    if n>2 and np.array_equal(U22, L22U22) and np.array_equal(L22, I22):
        return L, A  # Devuelve la matriz identidad y A original
    
    
    # Actualizamos las matrices L y U
    L[1:, 0] = L21
    U[0, 0] = u11
    U[0, 1:] = U12

    # Actualizamos las matrices L y U con los bloques calculados recursivamente
    L[1:, 1:] = L22
    U[1:, 1:] = U22
    
    return L, U

# Ejemplo de uso:
A = np.array([[1, 2, 0, 1], 
              [4, 3, 2, 5], 
              [2, 1, 0, 4], 
              [3, 2, 1, 0]])

B = np.array([[1, 2, 3],
              [2, 4, 6],
              [3, 6, 9]])

L, U = descompLU(A)

print("L:")
print(L)
print("U:")
print(U)

L:
[[1.  0.  0.  0. ]
 [4.  1.  0.  0. ]
 [2.  0.6 1.  0. ]
 [3.  0.8 0.5 1. ]]
U:
[[ 1.   2.   0.   1. ]
 [ 0.  -5.   2.   1. ]
 [ 0.   0.  -1.2  1.4]
 [ 0.   0.   0.  -4.5]]


In [ ]:
#ejercicio 2
def pos_del_Max(f):
    Max = 0
    pos = 0
    for i in range(len(f)):
        if abs(f[i]) > Max:
            Max = abs(f[i])
            pos = i
    return pos
            

def descompPLU(A):
    n = A.shape[0]
    
    #Caso Base/Matriz de 1x1
    if n == 1:
        if A[0, 0] == 0:
            print("Error: La Matriz tiene un 0 en la diagonal.")
            return np.eye(1), np.eye(1), A  
            # Printea error, pues el ultimo elemento de la diagonal es un 0 y no hay ningun otro elemnto para hacer el pivot
            # Devuelve P como la matriz identidad(dim = 1), L como la matriz identidad (dim = 1) y U como la matriz original A (en este paso de la recursion)
        else:
            return np.eye(1), np.array([[1]]), A  
            # Devuelve P como la matriz identidad(dim = 1), L como la matriz identidad (dim = 1) y U como la matriz original A (en este paso de la recursion)
    
    #Definiciones de bloques
         
    a11 = A[0, 0] # Obs: Python guarda este valor como un float  
    A12 = A[0, 1:]
    A21 = A[1:, 0] # Obs: Python guarda este vector en formato horizontal
    A22 = A[1:, 1:]

    #Definiciones de matrices complementarias
    
    P = np.eye(n)  # Matriz identidad de nxn
    P22 = np.eye(n-1) # Matriz identidad menor
    L = P
    U = np.zeros((n, n))  # Matriz de ceros de nxn
    
    
    # Calculos:
    
    # Hacemos el Pivot (de ser necesario)
    if a11 == 0:
        k = pos_del_Max(A21)+1 # Tomamos la posicion del elemento con mayor valor absoluto en la primer fila de A
        # el +1 es porque se agrega la posicion que ocupa a11
        
        # Intercambiamos las filas en A
        fila_A_k = A[k,0:] # guarda la fila A_K
        A[k, 0:] = A[0, 0:] # paso la fila A_0 a la fila A_k
        A[0, 0:] = fila_A_k #paso la fila A_k a la fila A_0

        # Intercambiamos las filas en P (cabe recalcar que en este paso del algoritmo da igual intercambiar filas o intercambiar columnas)
        fila_P_k = P[k,0:] # guarda la fila P_K
        P[k, 0:] = P[0, 0:] # paso la fila P_0 a la fila P_k
        P[0, 0:] = fila_P_k #paso la fila P_k a la fila P_0
    
    # Calculamos u11 y U12
    u11 = a11
    U12 = A12
    
    # Calculamos L21
    L21 = A21 / u11
    
    # LLEGUÉ HASTA ACÁ, MAS O MENOS, TERMINAR
    
    # Calculamos L22 y U22 recursivamente
    L22U22 = A22 - L21.reshape(-1,1)@U12.reshape(1,-1)
    P22, L22, U22 = descompLU(L22U22)
    
    #print("L22:")
    #print(L22)
    #print("U22:")
    #print(U22)
    #print("L22U22:")
    #print(L22U22)
    
    if n>2 and np.array_equal(U22, L22U22) and np.array_equal(L22, I22):
        return P, L, A  # Devuelve la matriz identidad y A original
    
    
    # Actualizamos las matrices L y U
    L[1:, 0] = L21
    U[0, 0] = u11
    U[0, 1:] = U12

    # Actualizamos las matrices L y U con los bloques calculados recursivamente
    L[1:, 1:] = L22
    U[1:, 1:] = U22
    
    return L, U

# Ejemplo de uso:
A = np.array([[1, 2, 0, 1], 
              [4, 3, 2, 5], 
              [2, 1, 0, 4], 
              [3, 2, 1, 0]])

B = np.array([[1, 2, 3],
              [2, 4, 6],
              [3, 6, 9]])

L, U = descompLU(A)

print("L:")
print(L)
print("U:")
print(U)
    

In [11]:
#ejercicio 3
def resolverLU(A, b):
    L, U = descompLU(A)
    
    y = sc.linalg.solve_triangular(L,b, lower = True)
    res = sc.linalg.solve_triangular(U, y)
    return res
print(resolverLU(A, [1,2,3,4]))



[ 2.44444444 -0.55555556 -2.22222222 -0.33333333]


In [12]:
#ejercicio 4
A= np.random.rand(10,10)*2 - 1



 

[[-0.30140916 -0.33036098 -0.48115059  0.8875744  -0.75281325 -0.51780613
   0.52462836  0.62320279  0.69114993 -0.86291683]
 [ 0.00736308  0.28660567 -0.1819869  -0.14517101 -0.0294156   0.06494322
  -0.86647477  0.8750588  -0.80316086 -0.48681619]
 [ 0.82106191 -0.65490314  0.32636492 -0.9597872  -0.86335173 -0.89306948
   0.20346559  0.92725387  0.01128638  0.85853988]
 [-0.58699092 -0.44124115 -0.8360802   0.46491476  0.52454957  0.67881339
   0.73571271 -0.14168504  0.62645043 -0.64558305]
 [-0.4869252  -0.30209931  0.96891059 -0.06010344  0.24110385 -0.48920558
   0.80404459 -0.37772544 -0.3570756   0.75601192]
 [-0.54153935 -0.63233256  0.81807619 -0.62251077  0.00345767 -0.76962727
   0.22991324  0.32353093  0.0359607  -0.62309328]
 [-0.85797643  0.66529898 -0.11081926  0.12255345 -0.64790679  0.21536455
  -0.07535831 -0.57444601  0.95645901  0.92344194]
 [ 0.29252162  0.26941299 -0.02840092  0.50080825 -0.61664371 -0.03392803
  -0.45495898 -0.69061374  0.02628723 -0.02441924]
